services:
  bastion:
    build:
      context: machines/bastion
      dockerfile: Dockerfile
    hostname: vera-bastion
    volumes:
      - ./flags/flag1:/flag
    ports:
      - 8080:80
    networks:
      - public_net
      - private_net

  backups:
    build:
      context: machines/backups
      dockerfile: Dockerfile
    hostname: vera-backups
    volumes:
      - ./flags/flag2:/flag
    ports:
      - 22:22
      - 21:21
    networks:
      - private_net

  smtp:
    build:
      context: machines/smtp
      dockerfile: Dockerfile
    hostname: vera-smtp
    volumes:
      - ./flags/flag3:/flag
    ports:
      - 22:22
    networks:
      - private_net

networks:
  public_net:
    driver: bridge
  private_net:
    driver: bridge
    internal: true